= Keep: English Learn
:icons: font
:published_at: 2017-01-04
:hp-tags: keep, notes, english, learn, links
---

#*Iniciante*#

1. (https://www.udemy.com/cursodeinglesbasico25/)[Curso de Inglês Básico Começando de Zero Entenda 25%]
1. (https://www.duolingo.com/)[Duolingo]
1. (https://www.memrise.com/)[Memrise]
1. (http://aulasdeinglesgratis.net/textos-em-ingles-para-iniciantes-com-audio/)[Textos em Inglês para Iniciante]

#*Básico*#

Canal do Beto Ferreira - Nível Básico
https://www.youtube.com/playlist…
Canal Inglês Winner - Nível Básico
https://www.youtube.com/playlist?list=PL7BDB07039775D0A6
App do Inglês Winner - Acesso a todas as aulas
https://play.google.com/store/apps/details…
Guia Definitivo - Mairo Vergara
http://www.mairovergara.com/caigdg
Mini-aulas e Dicas de Inglês - Mairo Vergara
https://www.youtube.com/user/MairoVergara/playlists
Livros / Dicionário ou tradutor para analisar pronuncia
http://www.fiction.us/

#*Conversação*#

1. https://www.eslpod.com/website/show_all.php?cat_id=-39570#[Podcast - Want to be Fluent in English?]
1. http://aprenderpalavras.com/curso-de-ingles-mairo-vergara/[Curso Mairo Vergara 3.0 - Pago ou Deep Web]
1. http://aulasdeinglesgratis.net/100-conversacoes-em-ingles/[100 Conversações - Texto EN/PT]
1. http://aulasdeinglesgratis.net/100-textos-em-ingles-com-traducao-e-audio/[Textos em InglêsPortuguês e Áudio]
1. https://www.youtube.com/channel/UCGxIAAnrhkCy6H2DRz-t6Qw[Aprenda Inglês se Divertindo - Tim Explica (Gringo)]
1. https://www.edx.org/course/conversational-english-skills-tsinghuax-30640014x-1[Conversational English Skills (EDX)]

#*Complemento*#

*_Inglês com Seriados (Friends, How i met your Mother, Everybody hates Chris e My Wife & Kids)_*

1. *Método*:
- Passo 1 - Dublagem original / Legenda Português
- Passo 2 - Dublagem original / Legenda Inglês
- Passo 3 - Dublagem original / Sem legenda

*_Inglês com Filmes (Matrix, (500) Days of Summer, Toy Store, Para Sempre Alice, Harry Potter e The GodFather)_*

1. *Método*: _O mesmo usado para seriados, mas pode ser aplicado apenas em cenas com bastante dialogo._ 

	- Passo 1 - Dublagem original / Legenda Português    
	- Passo 2 - Dublagem original / Legenda Inglês
	- Passo 3 - Dublagem original / Sem legenda

#*Vlogs/Canais*#

School of Life https://www.youtube.com/user/schooloflifechannel/playlists
Crash Course
https://www.youtube.com/user/crashcourse/playlists
Youtuber Gamer - HappyConsoleGamer
https://www.youtube.com/channel/UC2vUKoTGIwNYq4LO0YWKPIg
Cultura Pop - PBS Idea Channel
https://www.youtube.com/channel/UC3LqW4ijMoENQ2Wv17ZrFJA
Science Channel - SciShow
https://www.youtube.com/user/scishow/featured

#*Indicação*#

https://www.youtube.com/watch?v=RY1r70I_Doo
https://www.youtube.com/channel/UCDyjlawtWnY7j1C2RyObZlg
https://www.youtube.com/channel/UCNirOQBP88BVoRZD0GtS9xQ
https://www.youtube.com/channel/UCskEPRzGlsYHs_a5SJyCXag
https://www.youtube.com/channel/UC15HDk6sVZvWFomxNTMr3zw
https://www.youtube.com/channel/UCcNm9fM9V5wf-0PZVmkM08g
https://www.youtube.com/channel/UCX1Khol-7w7ZUbDPngo_-0g

#*Extensões do Chrome*#


> Fonte https://goo.gl/oeWUdp[Lucas Santana]